### ISSUE TITLE
ParallelClientSchedulerAndCancelTest fix

### ISSUE THREAD

**Issue by jeffpeiyt** [eBay/parallec#11]
ConcurrentModificationException

https://travis-ci.org/eBay/parallec#L2385

```java

hitTop100WebsitesCapacityProtectionCancel2ndTask(io.parallec.core.main.http.scheduler.ParallelClientSchedulerAndCancelTest)  Time elapsed: 4.037 sec  <<< ERROR!
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:413)
	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:412)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:206)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219)
	at com.google.gson.Gson.toJson(Gson.java:600)
	at com.google.gson.Gson.toJson(Gson.java:579)
	at com.google.gson.Gson.toJson(Gson.java:534)
	at com.google.gson.Gson.toJson(Gson.java:514)
	at io.parallec.core.util.PcStringUtils.renderJson(PcStringUtils.java:105)
	at io.parallec.core.ParallelTask.prettyPrintInfo(ParallelTask.java:758)
	at io.parallec.core.main.http.scheduler.ParallelClientSchedulerAndCancelTest.hitTop100WebsitesCapacityProtectionCancel2ndTask(ParallelClientSchedulerAndCancelTest.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)


```

**Comment by jeffpeiyt** [comment]
Root cause:  change aggregateResultMap to ConcurrentHashMap
