### ISSUE TITLE
Https Issues

### ISSUE THREAD

**Issue by medamineosm** [eBay/parallec#69]
2017-10-05 16:49:09.707 ERROR 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_96, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.706+0200, receiveTimeInManager=2017.10.05.16.49.09.706+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=0, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.708 ERROR 50106 --- [t-dispatcher-12] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_97, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.707+0200, receiveTimeInManager=2017.10.05.16.49.09.708+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=1, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.709 ERROR 50106 --- [t-dispatcher-12] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_18, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.709+0200, receiveTimeInManager=2017.10.05.16.49.09.709+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=1, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.710  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : 
[95]__RESP_RECV_IN_MGR 95 (+4) / 99 (95,960%)  AFT 0.186 S @ API_19 @ 2017.10.05.16.49.09.710+0200 , TaskID : 181dfd4c-062 , CODE: NA, RESP_BRIEF: EMPTY , ERR: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
2017-10-05 16:49:09.711 ERROR 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_19, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.710+0200, receiveTimeInManager=2017.10.05.16.49.09.710+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=1, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.712  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : 
[96]__RESP_RECV_IN_MGR 96 (+3) / 99 (96,970%)  AFT 0.188 S @ API_14 @ 2017.10.05.16.49.09.712+0200 , TaskID : 181dfd4c-062 , CODE: NA, RESP_BRIEF: EMPTY , ERR: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
2017-10-05 16:49:09.712 ERROR 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_14, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.711+0200, receiveTimeInManager=2017.10.05.16.49.09.711+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=0, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.713  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : 
[97]__RESP_RECV_IN_MGR 97 (+2) / 99 (97,980%)  AFT 0.189 S @ API_15 @ 2017.10.05.16.49.09.713+0200 , TaskID : 181dfd4c-062 , CODE: NA, RESP_BRIEF: EMPTY , ERR: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
2017-10-05 16:49:09.713 ERROR 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_15, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.713+0200, receiveTimeInManager=2017.10.05.16.49.09.713+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=1, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.714  INFO 50106 --- [lt-dispatcher-4] i.p.c.actor.AssistantExecutionManager    : Now finished sending all needed messages. Done job of ASST Manager at 2017.10.05.16.49.09.714+0200
2017-10-05 16:49:09.714  INFO 50106 --- [t-dispatcher-22] io.parallec.core.actor.ExecutionManager  : 
[98]__RESP_RECV_IN_MGR 98 (+1) / 99 (98,990%)  AFT 0.19 S @ API_16 @ 2017.10.05.16.49.09.714+0200 , TaskID : 181dfd4c-062 , CODE: NA, RESP_BRIEF: EMPTY , ERR: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
2017-10-05 16:49:09.715 ERROR 50106 --- [t-dispatcher-22] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_16, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.714+0200, receiveTimeInManager=2017.10.05.16.49.09.714+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=1, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.716  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : 
[99]__RESP_RECV_IN_MGR 99 (+0) / 99 (100,00%)  AFT 0.192 S @ API_17 @ 2017.10.05.16.49.09.716+0200 , TaskID : 181dfd4c-062 , CODE: NA, RESP_BRIEF: EMPTY , ERR: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
2017-10-05 16:49:09.716 ERROR 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : Error handling onCompleted in manager for response: ResponseOnSingleTask [request=TaskRequest [actorMaxOperationTimeoutSec=15, resourcePath=/v2/domain-search?domain=stripe.com&api_key=a650bb263194e27312facd0a873d736be1c78b73&api_key=a650bb263194e27312facd0a873d736be1c78b73, requestContent=, httpMethod=GET, pollable=false, httpHeaderMap={}, protocol=https, host=API_17, hostUniform=api.hunter.io, port=80, sshMeta=null, tcpMeta=null, udpMeta=null, pingMeta=null, handler=null, responseContext=null, responseHeaderMeta=null], responseContent=null, receiveTime=2017.10.05.16.49.09.716+0200, receiveTimeInManager=2017.10.05.16.49.09.716+0200, error=true, errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:188)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:146)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:123)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:484)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:227)
	at io.parallec.core.actor.HttpWorker.onReceive(HttpWorker.java:215)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
, statusCode=NA, statusCodeInt=-1, operationTimeMillis=2, pollingHistoryMap={}, responseHeaders=null] Error null
2017-10-05 16:49:09.716  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : task.state : COMPLETED_WITHOUT_ERROR
2017-10-05 16:49:09.716  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : task.totalJobNumActual : 99 InitCount: 99
2017-10-05 16:49:09.716  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : task.response received Num 99 
2017-10-05 16:49:09.716  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : SUCCESSFUL GOT ON ALL RESPONSES: Received all the expected messages. Count matches: 99 at time: 2017.10.05.16.49.09.716+0200
2017-10-05 16:49:09.717  INFO 50106 --- [       Thread-3] i.p.core.task.ParallelTaskManager        : !!COMPLETED sendTaskToExecutionManager : PT_99_20171005164909513_181dfd4c-062 at 2017-10-05 16:49:09.717+0200  		  GenericResponseMap in future size: 99
2017-10-05 16:49:09.717  INFO 50106 --- [t-dispatcher-20] io.parallec.core.actor.ExecutionManager  : 
Time taken to get all responses back : 0.193 secs
2017-10-05 16:49:09.718  INFO 50106 --- [       Thread-3] i.p.core.task.ParallelTaskManager        : Removed task PT_99_20171005164909513_181dfd4c-062 from the running inprogress map... . This task should be garbage collected if there are no other pointers.
2017-10-05 16:49:10.019  INFO 50106 --- [           main] io.parallec.core.ParallelTaskBuilder     : ***********FINISH_PARALLEL_HTTP_TASK_PT_99_20171005164909513_181dfd4c-062***********
2017-10-05 16:49:10.019  INFO 50106 --- [           main] io.parallec.core.ParallelClient          : Releasing all ParallelClient resources... 
2017-10-05 16:49:10.019  INFO 50106 --- [           main] io.parallec.core.actor.ActorConfig       : shutting down actor system...
2017-10-05 16:49:10.042  INFO 50106 --- [           main] io.parallec.core.actor.ActorConfig       : Actor system has been shut down.
2017-10-05 16:49:10.045  INFO 50106 --- [           main] io.parallec.core.ParallelClient          : Have released all ParallelClient resources (actor system + async+sync http client + task queue)
Now safe to stop your application.

**Comment by jeffpeiyt** [comment]
This looks like a maven dependency hell issue with different versions.

**Comment by medamineosm** [comment]
How can i resolved !
this my pom.xml
![image](https://user-images.githubusercontent.com/5613773/31267529-be3186aa-aa78-11e7-8c4f-9b533311459d.png)

**Comment by jeffpeiyt** [comment]
Here are some links:
https://stackoverflow.com/questions/33907162/systematic-approach-with-maven-to-deal-with-dependency-hell

https://carlosbecker.com/posts/maven-dependency-hell/

```
errorMessage=java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection, stackTrace=java.lang.ClassCastException: 
```

**Comment by jeffpeiyt** [comment]
Closing the issue for now and feel free to reopen if there are still questions. Thanks.
