### ISSUE TITLE
Check url protocol in setting up target host

### ISSUE THREAD

**Issue by djKooks** [eBay/parallec#72]
Hello.
I just found some issue from this code.
```
ParallelClient pc = new ParallelClient();
        pc.prepareHttpGet("").setTargetHostsFromString("https://www.google.co.jp")
            .execute(new ParallecResponseHandler() {
                public void onCompleted(ResponseOnSingleTask res,
                                        Map<String, Object> responseContext) {
                    System.out.println( res.toString() );  }
            });
```

This shows error logs.
```
11:37:30.353 [ParallecActorSystem-akka.actor.default-dispatcher-3] DEBUG io.parallec.core.actor.HttpWorker - AHC completeUrl http://https://www.google.co.jp:80
11:37:30.716 [AsyncHttpClient-Callback] DEBUG c.n.h.c.p.jdk.JDKAsyncHttpProvider - https
java.net.UnknownHostException: https
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_102]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_102]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_102]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_102]
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider$AsyncHttpUrlConnection.call(JDKAsyncHttpProvider.java:245) ~[async-http-client-1.6.5.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

Yes, this happens because protocol is being attached though it already has one.
I thought about filtering url in `OperationWorker.processMainRequest`, but not sure about architecture concept. How do you think?

Thanks.

**Comment by jeffpeiyt** [comment]
@djKooks  Hi Dennis, I think the problem is the documentation about how to set the https is not clear enough. Probably need to add an example in the doc. Please try and let me know.

you can follow this example to make the change: https://github.com/eBay/parallec/blob/master/src/test/java/io/parallec/core/main/http/ParallelClientHttpBasicMoreOptionsTest.java#L125 
```
        .setProtocol(RequestProtocol.HTTPS)
        .setHttpPort(443)
        .setTargetHostsFromString("www.rakuten.co.jp")
```

**Comment by djKooks** [comment]
@jeffpeiyt Thanks!
But there are little problem in usage, cause maybe someone just could copy&paste URL from browser, and it copies address which includes protocol. I think it also needs to comment to remove protocol in target host in implementation.

**Comment by jeffpeiyt** [comment]
@djKooks  yes.  It is a valid concern when pasting the URLs.   However we not just support HTTP, but also tcp/udp etc.   We should not put the urls into the `target host` part.   But I agree that we have much room to improve on the HTTPS example and add documentation to reduce confusion on where to put the prototol part.  :-)
