### ISSUE TITLE
Error when build Jar file w/ this library

### ISSUE THREAD

**Issue by roquie** [eBay/parallec#77]
Hi!

I created new project with intellij and copy-paste your ping example, then I attempts to build jar file, but receive following error:

```
19:43:28.662 [main] INFO  i.p.core.task.ParallelTaskManager - Initialized ParallelTaskManager...
19:43:28.669 [main] INFO  i.p.c.r.AsyncHttpClientFactoryEmbed - FastClient: ningFastClientConnectionTimeoutMillis: 4000
19:43:28.670 [main] INFO  i.p.c.r.AsyncHttpClientFactoryEmbed - FastClient: ningFastClientRequestTimeoutMillis: 14000
19:43:28.721 [main] INFO  c.n.h.c.p.n.NettyAsyncHttpProvider - Number of application's worked threads is 0
19:43:28.722 [main] INFO  c.n.h.c.p.n.NettyAsyncHttpProvider - Number of application's worked threads is 0
19:43:28.722 [main] DEBUG com.ning.http.client.AsyncHttpClient - Default provider not found com.ning.http.client.providers.netty.NettyAsyncHttpProvider. Using the com.ning.http.client.providers.jdk.JDKAsyncHttpProvider
19:43:28.724 [main] INFO  c.n.h.c.p.n.NettyAsyncHttpProvider - Number of application's worked threads is 0
19:43:28.724 [main] INFO  c.n.h.c.p.n.NettyAsyncHttpProvider - Number of application's worked threads is 0
19:43:28.724 [main] DEBUG com.ning.http.client.AsyncHttpClient - Default provider not found com.ning.http.client.providers.netty.NettyAsyncHttpProvider. Using the com.ning.http.client.providers.jdk.JDKAsyncHttpProvider
19:43:28.822 [main] INFO  io.parallec.core.ParallelClient - Initialing Parallel Client Resources: actor system, HttpClientStore, Task Manager ....
19:43:28.872 [main] DEBUG io.parallec.core.actor.ActorConfig - Load Actor config Config(SimpleConfigObject({"akka":{"actor":{"deployment":{"default":{"cluster":{"allow-local-routees":"on","enabled":"off","max-nr-of-instances-per-node":1,"routees-path":"","use-role":""},"metrics-selector":"mix"}},"router":{"type-mapping":{"adaptive-group":"akka.cluster.routing.AdaptiveLoadBalancingGroup","adaptive-pool":"akka.cluster.routing.AdaptiveLoadBalancingPool"}},"serialization-bindings":{"akka.cluster.ClusterMessage":"akka-cluster"},"serializers":{"akka-cluster":"akka.cluster.protobuf.ClusterMessageSerializer"}},"cluster":{"auto-down":"off","auto-down-unreachable-after":"off","failure-detector":{"acceptable-heartbeat-pause":"3 s","expected-response-after":"5 s","heartbeat-interval":"1 s","implementation-class":"akka.remote.PhiAccrualFailureDetector","max-sample-size":1000,"min-std-deviation":"100 ms","monitored-by-nr-of-members":5,"threshold":8},"gossip-different-view-probability":0.8,"gossip-interval":"1s","gossip-time-to-live":"2s","jmx":{"enabled":"on"},"leader-actions-interval":"1s","log-info":"on","metrics":{"collect-interval":"3s","collector-class":"akka.cluster.SigarMetricsCollector","enabled":"on","gossip-interval":"3s","moving-average-half-life":"12s"},"min-nr-of-members":1,"periodic-tasks-initial-delay":"1s","publish-stats-interval":"off","reduce-gossip-different-view-probability":400,"retry-unsuccessful-join-after":"10s","role":{},"roles":[],"scheduler":{"tick-duration":"33ms","ticks-per-wheel":512},"seed-node-timeout":"5s","seed-nodes":[],"unreachable-nodes-reaper-interval":"1s","use-dispatcher":""},"log-dead-letters":0,"log-dead-letters-during-shutdown":"off"},"awt":{"toolkit":"sun.lwawt.macosx.LWCToolkit"},"file":{"encoding":{"pkg":"sun.io"},"separator":"/"},"ftp":{"nonProxyHosts":"local|*.local|169.254/16|*.169.254/16"},"gopherProxySet":"false","http":{"nonProxyHosts":"local|*.local|169.254/16|*.169.254/16"},"java":{"awt":{"graphicsenv":"sun.awt.CGraphicsEnvironment","printerjob":"sun.lwawt.macosx.CPrinterJob"},"class":{"path":"pingdevice.jar","version":"53.0"},"home":"/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home","io":{"tmpdir":"/var/folders/mn/408nkh3s3d9cxfwzv2_t8q900000gn/T/"},"library":{"path":"/Users/roquie/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."},"runtime":{"name":"Java(TM) SE Runtime Environment","version":"9.0.1+11"},"specification":{"name":"Java Platform API Specification","vendor":"Oracle Corporation","version":"9"},"vendor":{"url":{"bug":"http://bugreport.java.com/bugreport/"}},"version":"9.0.1","vm":{"compressedOopsMode":"Zero based","info":"mixed mode","name":"Java HotSpot(TM) 64-Bit Server VM","specification":{"name":"Java Virtual Machine Specification","vendor":"Oracle Corporation","version":"9"},"vendor":"Oracle Corporation","version":"9.0.1+11"}},"jdk":{"debug":"release"},"line":{"separator":"\n"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.13.2"},"path":{"separator":":"},"socksNonProxyHosts":"local|*.local|169.254/16|*.169.254/16","sun":{"arch":{"data":{"model":"64"}},"boot":{"library":{"path":"/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/lib"}},"cpu":{"endian":"little","isalist":""},"io":{"unicode":{"encoding":"UnicodeBig"}},"java":{"command":"pingdevice.jar","launcher":"SUN_STANDARD"},"jnu":{"encoding":"UTF-8"},"management":{"compiler":"HotSpot 64-Bit Tiered Compilers"},"os":{"patch":{"level":"unknown"}}},"user":{"country":"US","dir":"/Users/roquie/google_drive/experiments/crystal/pingdevice/out/artifacts/pingdevice_jar","home":"/Users/roquie","language":"en","name":"roquie","timezone":"Europe/Moscow"}}))
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.parallec.core.ParallelClient.initialize(ParallelClient.java:114)
	at io.parallec.core.ParallelClient.<init>(ParallelClient.java:105)
	at Ping.main(Ping.kt:16)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:168)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:504)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:118)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:66)
	at akka.actor.ActorSystem.create(ActorSystem.scala)
	at io.parallec.core.actor.ActorConfig.<clinit>(ActorConfig.java:48)
	... 3 more
```

I'm use Gradle with Kotlin DSL. Also I tried use `shadowJar` (http://imperceptiblethoughts.com/shadow/) with following config:

```
tasks {
    "shadowJar"(ShadowJar::class) {
//        transform(AppendingTransformer::class.java) {
//            resource = "reference.conf"
//        }
        append("reference.conf")
    }
}
```
`reference.conf` file is exist in root of jar file, but program still not working. 
How to build it is into jar file?

**Comment by jeffpeiyt** [comment]
@roquie seems to be a more generic problem with akka 

https://stackoverflow.com/questions/31011243/no-configuration-setting-found-for-key-akka-version

Feel free to google the error too.

**Comment by roquie** [comment]
Maybe it is solution for Maven, but I have a problems with Gradle. It says what need to be use `maven-shade-plugin` for Maven... and I tryed to use analogue for Gradle  like as `shadow-plugin`. Second block with code in first post is a same code about says in stackoverflow, but for Gradle.

**Comment by roquie** [comment]
Also, I found this solution http://www.sureshpw.com/2015/10/building-akka-bundle-with-all.html but it isn't work (just copy-paste cluster `reference.conf` file without merging with others).

**Comment by roquie** [comment]
Solution. https://github.com/akka/akka/issues/24248

@jeffpeiyt thanks for answer, you created awesome library :)

P.S. Without Kotlin DSL all works.
